### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by rumtraubenuss** [garytryan/cy-mock-graphql#7]
There are some minor issue in the README. See #6
Gave me some headache after copy and paste from the README ;-) 

Maybe it also worth mentioning in the README that the name of the npm package `cy-mock-graphql` differs from the github repo name?

BTW: Great cypress graphql mock plugin here!
I tried some other plugins for this task but did not get them to work.

**Comment by garytryan** [comment]
Thanks @rumtraubenuss! I've merged your PR and published the changes in v1.2.3. I've changed this repo name to match the library name.

I'm glad this is working for you. Thanks for contributing :)
